[package]
name = "wio_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atsamd-hal = "0.12.0"
embedded-hal = "0.2.7"
nb = "1.1.0"
